# Pipes              â•°â”€ â•­â”€
# Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’ 
# Wedges             ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# Random noise       ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—

# Icons
# î€‡ ï ¼ î¼  ï‹¾  âœ âœ— î² î› î—» î—½ î˜œ îš® ï¯ îš¨ î¹ª îœŠ îœ‰ îœˆ ï„“ îœ— î¬€ î®¡ îœ¥ îœ¦ îœ§ îœ¨ î©£
# î¾  ïŒµ îœŒ ïŠ“ ïŠ” î¯Š î¯‡  î¯„  î®² î¯§ î»   î¼ ï‚¡ ï„ ï†  ïˆ² ï‡­ ï‡´  ï‡¿  ïˆŸ  ïŒˆ
# ïŠ ï‰ ïŒš ï™ ï– ï• ï ï ï± ï° ï’„ ï’‰ ï’« ï“‰ ï“‡ ï“› ï“œ ï“  ï–® ï–¯ ï–± ï–² ï—¥ 
# ï¢ ïŸ¸ ï ’ ï ‹ î€ î€‚ î€ƒ î€„ îŠ¡ î½™ ï‚ ï… ï“™

add_newline = false

right_format = """\
$memory_usage$cmd_duration
"""
format = """
$hostname$username$directory$git_branch$git_status$c$golang
$character$shell
"""
# îƒ‚ îƒ€ 
[character]
success_symbol            = "[îƒ‚ ](bold fg:blue)[ïŒ“ ](bold bg:blue fg:black)[îƒ€](bold fg:blue)"
error_symbol              = "[îƒ‚ ](bold fg:red )[î™” ](bold bg:red  fg:black)[îƒ€](bold fg:red)"
vimcmd_symbol             = "[îƒ‚ ](bold fg:blue)[îŸ… ](bold bg:blue fg:black)[îƒ€](bold fg:blue)"
vimcmd_replace_one_symbol = "[îƒ‚ ](bold fg:blue)[îŸ… ](bold bg:blue fg:black)[îƒ€](bold fg:blue)"
vimcmd_replace_symbol     = "[îƒ‚ ](bold fg:blue)[îŸ… ](bold bg:blue fg:black)[îƒ€](bold fg:blue)"
vimcmd_visual_symbol      = "[îƒ‚ ](bold fg:blue)[îŸ… ](bold bg:blue fg:black)[îƒ€](bold fg:blue)"

[package]
disabled = true

[git_branch]
style             = "fg: blue"
symbol            = "ó°˜¬ "
truncation_length = 4
truncation_symbol = ""
format            = " [$symbol $branch(:$remote_branch)]($style)"

[git_commit]
commit_hash_length = 4
tag_symbol = "î«¼"

[git_state]
format      = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[îŠ› PICKING](bold red)"

[git_status]
conflicted = "ï€¤ "
ahead      = "ó°›ƒ "
behind     = "ó°›€ "
diverged   = "î®« " # ó°½œ ó°ƒ¸
untracked  = "î£ "
stashed    = "ïƒ‡ "
modified   = "ï„ª "
staged     = '[++\($count\)](blue)' # î¸© 
up_to_date = "ï€Œ "
renamed    = "ï‘š "
deleted    = "ï€ "
style = "fg:blue"
format = ' ($all_status$ahead_behind($style) )'

[git_metrics]
disabled = false

[hostname]
ssh_only = false
format   =  "[îƒ‚ ](bold fg:blue)[$hostname](bg:blue bold fg:black)[îƒ€ ](bold fg:blue)"
trim_at  = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled  = true
threshold = 5
symbol    = "ó°›"
style     = "dimmed blue"
format    = '$symbol [${ram}]($style) '

[time]
disabled    = true
format      = 'îƒ [\[ $time \]]($style) '
time_format = "%T"

[username]
disabled    = false
show_always = true
style_user  = "bold bg:blue fg:black"
style_root  = "red bold"
format      = "[îƒ‚ ](bold fg:black fg:blue)[$user]($style)[îƒ€ ](bold fg:black bg: blue)"

[directory]
home_symbol       = "ï€• "
read_only         = "ï€£ "
style             = "bold bg:blue fg:black"
truncation_length = 3
truncation_symbol = "â€¦/"
format            = '[îƒ‚ ](fg:blue)[$path]($style)[îƒ€ ](fg:blue)'

[directory.substitutions]
"documents" = "ó±”— "
"downloads" = "ó°‰ "
"music"     = "ó±™ "
"pictures"  = "ï€¾ "

[c]
style  = "fg: blue"
format = ' [î»¸  $version]($style)'

[golang]
style  = "fg: blue"
format = ' [îœ¤ $version]($style)'

[shell]
disabled = false
bash_indicator = 'ó±†ƒ '
fish_indicator = 'î¹ '
unknown_indicator = 'ï„¨ '
style = 'fg:black bg:#78a9ff'
format = '[îƒ‚ ](bold fg:#78a9ff)[$indicator]($style)[îƒ€ ](bold fg:#78a9ff)'

[cmd_duration]
disabled = true
min_time = 0
format   = '[îƒ… ](bold fg:#ee5396)[ó±« :$duration](bold fg:black bg:#ee5396)[îƒ„ ](bold fg:#ee5396)'

[os]
format   = "on [($name )]($style)"
style    = "bold blue"
disabled = true

# [os]
# disabled = true
# format='[$symbol]($style)'
# style='bold white'

[os.symbols]
Arch  = "ó°£‡"
NixOS = "ïŒ“"

