# Don't print a new line at the start of the prompt
add_newline = false
# Icons
# î€‡ ïŸ ï ¼ î¼  ï‹¾  âœ âœ— î² î› î—» î—½ î˜œ îš® ï¯ îš¨ î›“ î¹ª î› îœŠ îœ‰ îœˆ ï„“ îœ— î¬€ î®¡ îœ¥ îœ¦ îœ§ îœ¨ î©£
# î¾  ïŒµ îœŒ î¢» ïŠ“ ïŠ” î¯Š î¯‡  î¯„  î®² î¯§ î² î² î²¢ î²¤ î»   î¼ ï‚¡ ï„ ï†  ïˆ² ï‡­ ï‡´  ï‡¿  ïˆŸ  ïŒˆ
# ïŠ ï‰ ïŒš ï™ ï– ï• ï ï ï± ï° ï’„ ï’‰ ï’« ï“‰ ï“‡ ï“› ï“œ ï“  ï–® ï–¯ ï–° ï–± ï–² ï–³ ï—ˆ ï—¥ ï ï“ ï’
# ï¢ ï£ ïŸ‰ ïŸ¸ ï ’ ï ‹ ï ¡ ï ¢ ï £ ï ¤ ï¡¼ ï¡½ ï¡¾ ï¡¿ ï£© ï£ª ï£« ï£¬ ï£­ ï£® î€ î€‚ î€ƒ î€„ îŠ¡ î½™ ï‚ ï… ï“™
# Pipes â•°â”€ â•­â”€
# Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’ 
# Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# Random noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—

right_format = """\
$cmd_duration
"""

# $username$hostname$directory $git_branch
format = """
$directory$character
"""

# îƒŠ  îƒˆ 
# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[îƒŠ ](bold fg:blue)[ î€‡ ](bold bg:blue fg:#000000)[îƒˆ ](bold fg:blue)"
error_symbol   = "[îƒŠ ](bold fg:red)[ îš¨ ](bold bg:red fg:#000000)[îƒˆ ](bold fg:red)"

vimcmd_symbol             = "[îƒŠ ](bold fg:blue)[ îŸ… ](bold bg:blue fg:#000000)[îƒˆ ](bold fg:blue)"
vimcmd_replace_one_symbol = "[îƒŠ ](bold fg:blue)[ îŸ… ](bold bg:blue fg:#000000)[îƒˆ ](bold fg:blue)"
vimcmd_replace_symbol     = "[îƒŠ ](bold fg:blue)[ îŸ… ](bold bg:blue fg:#000000)[îƒˆ ](bold fg:blue)"
vimcmd_visual_symbol      = "[îƒŠ ](bold fg:blue)[ îŸ… ](bold bg:blue fg:#000000)[îƒˆ ](bold fg:blue)"
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg: green"
symbol = "ó°˜¬"
truncation_length = 4
truncation_symbol = ""
format = "[îƒŠ ](bold fg:green)[$symbol $branch(:$remote_branch)](fg:black bg:green)[îƒˆ ](bold fg:green)"
# îƒŠ  îƒˆ 

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = " ğŸ³ "
ahead = " ğŸğŸ’¨ "
behind = " ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤· â€"
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](blue)'
renamed = " âœï¸ "
deleted = " ğŸ—‘ "

[hostname]
ssh_only = false
format =  "[î‚¼ ](bold bg:cyan fg:blue)[$hostname](bg:cyan bold fg:#000000)[î‚¼ ](bold fg:cyan bg:blue)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed blue"

[time]
disabled = true
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:blue fg:#000000"
style_root = "red bold"
format = "[îƒŠ ](bold fg:blue)[$user]($style)îƒˆ "
# îƒŠ  îƒˆ 
disabled = false
show_always = true

[directory]
home_symbol = "ïŸ"
# root_symbol = "î­†"
read_only = " ï€£ "
style = "bold bg:blue fg:#000000"
truncation_length = 3
truncation_symbol = "â€¦/"
format = '[îƒŠ ](fg:blue)[$path]($style)[îƒˆ ](fg:blue)'


[directory.substitutions]
"documents" = "ïœ˜"
# "/" = " îˆ¯ "
"downloads" = " ï€™ "
"music" = " ï€ "
"pictures" = " î˜ "
"videos" = " î› "
"vault" = " ï "
"personal" = " ï‹ "
"notes" = " \uf24a "
"library" = " \uf02d "
"demos" = " î¼ "
"qemu" = " ï ¡ "

[c]
format = 'via [$name $version]($style)'

[cmd_duration]
disabled = true
min_time = 0
format = '[ğŸ¬ˆğŸ¬–ğŸ¬¥ğŸ¬… ](bold bg:yellow fg:#000000)[time:$duration](bold bg:yellow fg:#000000)[ ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—](bold bg:yellow fg:#000000)'
